# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "avada sample app embed"
client_id = "ebacb85ac65eef49580f3662abba24ce"
application_url = "https://produces-totally-bulk-terrible.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://produces-totally-bulk-terrible.trycloudflare.com/auth/shopify/callback",
  "https://produces-totally-bulk-terrible.trycloudflare.com/authSa/shopify/callback",
  "https://produces-totally-bulk-terrible.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "thomas-air-review-local-1.myshopify.com"
