# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc7740a99cb904a3eaf571da028e670d"
name = "search-tool"
handle = "search-tool"
application_url = "https://feelings-slovenia-rounds-resort.trycloudflare.com/auth/shopify"
embedded = true

[webhooks]
api_version = "2025-07"

[auth]
redirect_urls = [
  "https://feelings-slovenia-rounds-resort.trycloudflare.com/auth/shopify/callback",
  "https://feelings-slovenia-rounds-resort.trycloudflare.com/authSa/shopify/callback",
  "https://feelings-slovenia-rounds-resort.trycloudflare.com/auth/shopify/embed/callback",
  "https://feelings-slovenia-rounds-resort.trycloudflare.com/auth/shopify/embed/callback/updateScopes",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
